-- Relations Clear

delete from cart;
delete from author_email;
delete from owner_email;
delete from publisher_email;
delete from customer_email;
delete from publisher_bank;
delete from region;
delete from address;
delete from author;
delete from publisher;
delete from book;
delete from owner;
delete from customer;
delete from reports;
delete from checkout;
delete from orders;
delete from cart_books;
delete from book_author;
delete from author_phone_number;
delete from owner_phone_number;
delete from customer_phone_number;
delete from publisher_phone_number;